### ISSUE TITLE
Why not GUI?

### ISSUE THREAD

**Issue by ssoriche** [Lokaltog/vim-distinguished#1]
Sorry I'm relatively new to Vim scripting.

Why wouldn't this theme work with a GUI? I really like the look of powerline, and wanted to see how the distinguished would look as my colour scheme.

Thanks!

~Shawn

**Comment by Lokaltog** [comment]
The latest version on the develop branch supports the GUI.

**Comment by ssoriche** [comment]
Thanks, didn't realize it was there. I've set it up now, looks nice.

~Shawn
