### ISSUE TITLE
cursorline on terminal

### ISSUE THREAD

**Issue by Massimo-B** [Lokaltog/vim-distinguished#4]
Hi,
on 256 color terminal and using vim (not gvim) and set cursorline,
the line and the cursor are both nearly white and white and not distinguishable.

A darker gray for the line background would be nice.

![Uploading vim-distinguished.png . . .]()

Best regards,
Massimo

**Comment by Massimo-B** [comment]
![vim-distinguished](https://f.cloud.github.com/assets/3286728/77950/3077fd82-6165-11e2-8542-efc147e085df.png)

**Comment by Lokaltog** [comment]
Heh, yeah. The cursorline is actually meant to be used with something like NERDTree, but I've stopped using that as well so I haven't seen the cursorline for quite some time. I'll adjust it so it looks better. :)

**Comment by Massimo-B** [comment]
Thank you very much.
I use cursorline all the time, its not related to NERDTree.
I was using columnline too some day which looked very crazy like crosshair, but kills performance on some terminals :)
