### ISSUE TITLE
set background=dark causes the colorscheme not to load

### ISSUE THREAD

**Issue by scottchiefbaker** [Lokaltog/vim-distinguished#7]
If I `set background=dark` the theme doesn't load.

**Comment by Lokaltog** [comment]
Hm, not sure if this should matter. The theme sets it [here](https://github.com/Lokaltog/vim-distinguished/blob/develop/colors/distinguished.vim#L5), are you setting background=dark after loading the theme?

**Comment by scottchiefbaker** [comment]
Aha! Yes if I set background=dark AFTER the theme it does not load. It loads correctly if I set it BEFORE the theme. That must have been my issue.

**Comment by Lokaltog** [comment]
Allright! Not sure if it's even possible to fix this in the plugin itself (I guess `set background=dark` somehow resets the color scheme), so I'll close this issue.
